### ISSUE TITLE
Must Use One Template Per Source Server

### ISSUE THREAD

**Issue by RyTheITGuy** [aws-samples/drs-template-manager#5]
While testing this solution I observed that using a single template to cover multiple source servers will delete dynamic tags created by the DRS service in EC2 Launch Templates. Each launch template has two unique tags for both instance and volume ResourceTypes:

- **AWSElasticDisasterRecoverySourceServerID**
- **Name**

Internal DRS tooling requires these tags.

To resolve, create a single json file per source server and upload to the S3 bucket. You will need to tag each source server with the corresponding json file prefix, too. Replace the TagSpecifications with the code below. Update **AWSElasticDisasterRecoverySourceServerID** and  **Name** with the corresponding SourceServerID and Name for the source server. 

```
    "TagSpecifications": [
        {
            "ResourceType": "volume",
            "Tags": [
                {
                    "Key": "AWSElasticDisasterRecoverySourceServerID",
					"Value": "s-xxxxxxxxxxxxxxxxx"
                },
                {
                    "Key": "Name",
                    "Value": "YourServerNameHere"
                },
                {
                    "Key": "AWSElasticDisasterRecoveryManaged",
                    "Value": "drs.amazonaws.com"
                }
            ]
        },
        {
            "ResourceType": "instance",
            "Tags": [
                {
                    "Key": "AWSElasticDisasterRecoverySourceServerID",
					"Value": "s-xxxxxxxxxxxxxxxxx"
                },
                {
                    "Key": "Name",
                    "Value": "YourServerNameHere"
                },
                {
                    "Key": "AWSElasticDisasterRecoveryManaged",
                    "Value": "drs.amazonaws.com"
                }
            ]
        }
    ],
```

While you can retrieve source server IDs and Names from the console, I was able to get a list of source servers with the following CLI:

`aws drs --region region describe-source-servers > sources.txt
`

The CLI above output a JSON file. I then used a JSON to CSV converter to allow for easier reading of the SourceServerIDs and Names. It's also possible to use tools like Word Mail Merge, or similar, to merge the SourceServerID and Name tags into new JSON files.

**Comment by lewinkedrs** [comment]
Closing this issue since fix was merged via PR https://github.com/aws-samples/drs-template-manager/pull/6
